---
title: "Template"
author:
- Author One
- Author Two
date: 'YYYY-MM-DD (updated: `r Sys.Date()`) '
output:
  pdf_document: 
    toc: true
    toc_depth: 2
urlcolor: blue
---

```{r setup, include=FALSE}
# By default, all codes are hidden.
knitr::opts_chunk$set(message = FALSE, warning = FALSE, include = TRUE, echo = FALSE, eval = TRUE, comment = NA, tab.topcaption = TRUE)
library(haven)
library(knitr)
library(tidyverse)
library(here)
library(workshopr)
library(flextable)
set_flextable_defaults(font.size = 11, padding = 3)
# use_df_printer()
```

More options yaml please see posts here: https://rstudio.github.io/distill/basics.html
# Introduction

This document is to demonstrate some rmd basic functions.

# Visualization

When you compile the rmd, plots can be generated automatically.

```{r, include = TRUE, eval=TRUE, echo=TRUE}
cbPalette <- c(
  "#A50026", "#D73027", "#F46D43", "#FDAE61", "#FEE090", "#FFFFBF",
  "#E0F3F8", "#ABD9E9", "#74ADD1", "#4575B4", "#313695"
)
fake_data %>%
  select(Lopnr, contains("mmse")) %>%
  pivot_longer(
    cols = contains("mmse"),
    names_to = "wave", values_to = "mmse",
    names_prefix = "mmse_"
  ) %>%
  ggplot(aes(x = wave, y = mmse, fill = wave)) +
  geom_boxplot(na.rm = T) +
  scale_fill_manual(
    name = "MMSE Measures",
    values = cbPalette
  ) +
  labs(title = "Boxplots of MMSE Measures") +
  theme_minimal()
```

# Descriptive statistics

Just use `describe` from `psych` as an example. 

```{r , include = TRUE, eval=TRUE, echo=TRUE}
# install.packages('psych')
library(psych)

kable(describe(fake_data, na.rm = TRUE),
  format = "markdown",
  caption = "Example",
  digits = 2
)
```
