---
title: "Template"
author:
  - name: "Your Name"
    affiliation: "Your company/university"
date: 'YYYY-MM-DD (updated: `r Sys.Date()`) '
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    df_print: paged
---

```{r setup, include=FALSE}
# By default, all codes are hidden. 
knitr::opts_chunk$set(message = FALSE, warning = FALSE, include = TRUE)
library(workshopr)
library(tidyverse)
library(DT)
```

# Introduction

This document is to demonstrate rmd template with [rmdformats](https://cran.r-project.org/web/packages/rmdformats/readme/README.html) (HTML) output.

# Analysis

## Visualization

You can generate plots in HTML as in Word file.

```{r}
cbPalette <- c(
  "#A50026", "#D73027", "#F46D43", "#FDAE61", "#FEE090", "#FFFFBF",
  "#E0F3F8", "#ABD9E9", "#74ADD1", "#4575B4", "#313695"
)
fake_data %>%
  select(Lopnr, contains("mmse")) %>%
  pivot_longer(
    cols = contains("mmse"),
    names_to = "wave", values_to = "mmse",
    names_prefix = "mmse_"
  ) %>%
  ggplot(aes(x = wave, y = mmse, fill = wave)) +
  geom_boxplot(na.rm = T) +
  scale_fill_manual(
    name = "MMSE Measures",
    values = cbPalette
  )
```

## Table

One advantage of HTML is that you can have widget to demonstrate the data tabel. Really nice.

```{r}
DT::datatable(fake_data)
```

