---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# workshopr

<!-- badges: start -->
<!-- badges: end -->

The goal of `workshopr` is to make example data and script easily accessible.

## Installation

You can install the development version of workshopr from [GitHub](https://github.com/Bolin-Wu/workshopr):

``` r
install.packages("remotes")
remotes::install_github("Bolin-Wu/workshopr", subdir = "rpackage", force = TRUE)
```

## Data

```{r example_data, eval=FALSE}
workshopr::fake_snack_df 
```

## R script
### Loop 
[Xin Xia](https://ki-su-arc.se/staff/xin-xia/) leads this session. 
Load her example code:

```
workshopr::get_code_2023(session = "loop")
```

### Tidyverse & Rmarkdown
[Bolin](https://staff.ki.se/people/bolin-wu) leads this session.
Load the data:
```

```

Load example R code:
```
workshopr::get_code_2023(session = "tidyverse")
```

## Issues

You can raise bug reports [here](https://github.com/Bolin-Wu/workshopr/issues).
