#' paquid: factors of cognition decrease
#'
#' Factors of cognition decrease in paquid dataset.
#'
#' @source \url{https://www.rdocumentation.org/packages/lcmm/versions/1.8.1.1/topics/paquid}
#' @examples
#' \dontrun{
#'   # load data
#'   workshopr::paquid_cov
#'}
#'
"paquid_cov"

#' paquid: cognitive measures
#'
#' Measures of cognition related variables.
#'
#' @source \url{https://www.rdocumentation.org/packages/lcmm/versions/1.8.1.1/topics/paquid}
#'
#' @examples
#' \dontrun{
#'   # load data
#'   paquid_cog
#'   }
"paquid_cog"


#' Fake SNAC-K data
#'
#' A randomized SNAC-K data set, with metadata preserved.
#'
#' Random values are generated by \code{sample()}, \code{rnorm()} and \code{sample.int()}.
#'
#' @format A data frame with 15 variables and 3365 random obs.
"fake_snack_df"

