#' Fake SNAC-K data
#'
#' A randomized SNAC-K data set, with metadata preserved.
#'
#' Random values are generated by \code{sample()}, \code{rnorm()} and \code{sample.int()}.
#'
#' @format A data frame with 15 variables and 3365 random obs.
"fake_snack_df"

